services:
  mongo:
    build:
      context: ./database
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fink-network

  api:
    build:
      context: ./server
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - fink-network

  app:
    build:
      context: ./finkapp
    container_name: app
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - fink-network

volumes:
  mongo-data:

networks:
  fink-network:
    driver: bridge
