services:
  api:
    build:
      context: ./server
    container_name: api
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - PORT=${PORT}
      - API_URI=${API_URI}
      - WEBAUTHN_RPID=${WEBAUTHN_RPID}
      - WEBAUTHN_ORIGIN=${WEBAUTHN_ORIGIN}
    networks:
      - fink-network

  app:
    build:
      context: ./finkapp
    container_name: app
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - fink-network

networks:
  fink-network:
    driver: bridge
